import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { RefreshCw, Copy, Sparkles } from 'lucide-react';

// --- The Data (Customize these to be funny/techy) ---
const COLUMN_1 = [
  "Uber", "Tinder", "Spotify", "Airbnb", "ChatGPT", "Notion", "OnlyFans", "Discord", "Zoom", "Fitbit"
];
const COLUMN_2 = [
  "for Cats", "for Introverts", "for Plants", "for Babies", "for Aliens", "for Coders", "for Grandmas", "for Broke People", "for Robots"
];
const COLUMN_3 = [
  "on the Blockchain", "powered by AI", "but offline", "in the Metaverse", "subscription based", "but expensive", "governed by DAO", "made of wood", "underwater"
];

export default function IdeaGenerator() {
  const [idea, setIdea] = useState({ col1: "Uber", col2: "for Cats", col3: "on the Blockchain" });
  const [isSpinning, setIsSpinning] = useState(false);
  const [copied, setCopied] = useState(false);

  const spin = () => {
    if (isSpinning) return;
    setIsSpinning(true);
    setCopied(false);

    // Simulate slot machine "rolling" visual
    let count = 0;
    const interval = setInterval(() => {
      setIdea({
        col1: COLUMN_1[Math.floor(Math.random() * COLUMN_1.length)],
        col2: COLUMN_2[Math.floor(Math.random() * COLUMN_2.length)],
        col3: COLUMN_3[Math.floor(Math.random() * COLUMN_3.length)],
      });
      count++;
      if (count > 15) { // Stop after 15 shuffles
        clearInterval(interval);
        setIsSpinning(false);
      }
    }, 100); // Speed of shuffle
  };

  const copyToClipboard = () => {
    const text = `${idea.col1} ${idea.col2} ${idea.col3} - Generated by Akash's Portfolio`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="w-full py-8 bg-[#E6F9C9] font-sans flex flex-col items-center">
      
      <div className="max-w-2xl w-full px-6 text-center">
        
        {/* Header */}
        <div className="mb-8">
          <div className="inline-flex items-center gap-2 border-2 border-black bg-white px-3 py-1 rounded-full text-xs font-bold uppercase tracking-widest mb-4 shadow-[4px_4px_0px_0px_#000]">
            <Sparkles size={14} className="text-[#DFFF00] fill-black" />
            <span>Product Ideation Lab</span>
          </div>
          <h2 className="text-3xl md:text-4xl font-black uppercase leading-none mb-4">
            The Unicorn <br/> Generator
          </h2>
          <p className="font-medium text-gray-700">
            Can't find a project? Generate your next billion-dollar idea.
          </p>
        </div>

        {/* The Slot Machine Box */}
        <div className="bg-black p-4 rounded-3xl shadow-[10px_10px_0px_0px_rgba(0,0,0,0.2)]">
          <div className="flex flex-col md:flex-row gap-4 mb-4">
            {/* Slot 1 */}
            <div className="flex-1 bg-white h-24 rounded-xl flex items-center justify-center border-4 border-gray-800 relative overflow-hidden">
               <motion.span
                 key={idea.col1}
                 initial={{ y: -50, opacity: 0 }}
                 animate={{ y: 0, opacity: 1 }}
                 className="text-base md:text-lg font-black uppercase tracking-tighter"
               >
                 {idea.col1}
               </motion.span>
               <div className="absolute inset-0 shadow-[inset_0_0_20px_rgba(0,0,0,0.2)] pointer-events-none"></div>
            </div>

            {/* Slot 2 */}
            <div className="flex-1 bg-white h-24 rounded-xl flex items-center justify-center border-4 border-gray-800 relative overflow-hidden">
               <motion.span
                 key={idea.col2}
                 initial={{ y: 50, opacity: 0 }}
                 animate={{ y: 0, opacity: 1 }}
                 className="text-lg md:text-xl font-black uppercase tracking-tighter text-[#65a30d]"
               >
                 {idea.col2}
               </motion.span>
               <div className="absolute inset-0 shadow-[inset_0_0_20px_rgba(0,0,0,0.2)] pointer-events-none"></div>
            </div>

            {/* Slot 3 */}
            <div className="flex-1 bg-white h-24 rounded-xl flex items-center justify-center border-4 border-gray-800 relative overflow-hidden">
               <motion.span
                 key={idea.col3}
                 initial={{ y: -50, opacity: 0 }}
                 animate={{ y: 0, opacity: 1 }}
                 className="text-lg md:text-xl font-black uppercase tracking-tighter"
               >
                 {idea.col3}
               </motion.span>
               <div className="absolute inset-0 shadow-[inset_0_0_20px_rgba(0,0,0,0.2)] pointer-events-none"></div>
            </div>
          </div>

          {/* Controls */}
          <div className="flex gap-4">
            <button 
              onClick={spin}
              disabled={isSpinning}
              className="flex-1 bg-[#DFFF00] hover:bg-[#cce600] active:scale-95 transition-all text-black h-16 rounded-xl font-black text-lg uppercase tracking-widest border-b-4 border-r-4 border-black disabled:opacity-50 disabled:active:scale-100 flex items-center justify-center gap-2"
            >
              <RefreshCw size={24} className={isSpinning ? "animate-spin" : ""} />
              {isSpinning ? "Generating..." : "Generate Idea"}
            </button>
            
            <button 
              onClick={copyToClipboard}
              className="w-16 h-16 bg-gray-800 hover:bg-gray-700 active:scale-95 transition-all rounded-xl border-b-4 border-r-4 border-black flex items-center justify-center text-white"
              title="Copy Idea"
            >
              {copied ? <span className="text-xs font-bold">COPIED</span> : <Copy size={24} />}
            </button>
          </div>
        </div>
        
        <p className="text-xs font-bold uppercase tracking-widest text-gray-500 mt-4">
          *No refunds if you actually build this.
        </p>

      </div>
    </div>
  );
}